2017/07/20 12:15:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/20 12:16:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/20 12:18:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/20 12:18:41 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/20 12:18:42 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/20 12:18:43 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/20 12:18:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/20 12:18:47 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in C:\xampp\htdocs\yii-1.1\framework\gii\GiiModule.php:170
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#3 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/gii
---
2017/07/25 04:45:30 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '10/01/2016' for column 'hireDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 04:45:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '10/01/2016' for column 'hireDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 04:45:45 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '01/10/2016' for column 'hireDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 04:45:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '01/10/2016' for column 'hireDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 04:46:11 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '01-10-2016' for column 'hireDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 04:46:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '01-10-2016' for column 'hireDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 04:46:41 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 04:46:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 04:47:17 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 04:47:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 04:59:43 [error] [exception.CException] exception 'CException' with message 'Property "CStringValidator.0" is not defined.' in C:\xampp\htdocs\yii-1.1\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\validators\CValidator.php(177): CComponent->__set('0', 'email')
#1 C:\xampp\htdocs\yii-1.1\framework\base\CModel.php(287): CValidator::createValidator('length', Object(Employee), 'email', Array)
#2 C:\xampp\htdocs\yii-1.1\framework\base\CModel.php(260): CModel->createValidators()
#3 C:\xampp\htdocs\yii-1.1\framework\base\CModel.php(304): CModel->getValidators('departmentId')
#4 C:\xampp\htdocs\yii-1.1\framework\web\helpers\CHtml.php(1520): CModel->isAttributeRequired('departmentId')
#5 C:\xampp\htdocs\yii-1.1\framework\web\widgets\CActiveForm.php(600): CHtml::activeLabelEx(Object(Employee), 'departmentId', Array)
#6 C:\xampp\htdocs\yii-1.1\testdrive\protected\views\employee\_form.php(23): CActiveForm->labelEx(Object(Employee), 'departmentId')
#7 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\htdocs\yii-1.1\testdrive\protected\views\employee\create.php(18): CController->renderPartial('_form', Array)
#11 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#15 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(79): CController->render('create', Array)
#16 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#17 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#26 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#27 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#28 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/admin
---
2017/07/25 05:01:10 [error] [exception.CException] exception 'CException' with message 'Property "CEmailValidator.0" is not defined.' in C:\xampp\htdocs\yii-1.1\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\validators\CValidator.php(177): CComponent->__set('0', 'length')
#1 C:\xampp\htdocs\yii-1.1\framework\base\CModel.php(287): CValidator::createValidator('email', Object(Employee), 'email', Array)
#2 C:\xampp\htdocs\yii-1.1\framework\base\CModel.php(260): CModel->createValidators()
#3 C:\xampp\htdocs\yii-1.1\framework\base\CModel.php(304): CModel->getValidators('departmentId')
#4 C:\xampp\htdocs\yii-1.1\framework\web\helpers\CHtml.php(1520): CModel->isAttributeRequired('departmentId')
#5 C:\xampp\htdocs\yii-1.1\framework\web\widgets\CActiveForm.php(600): CHtml::activeLabelEx(Object(Employee), 'departmentId', Array)
#6 C:\xampp\htdocs\yii-1.1\testdrive\protected\views\employee\_form.php(23): CActiveForm->labelEx(Object(Employee), 'departmentId')
#7 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\htdocs\yii-1.1\testdrive\protected\views\employee\create.php(18): CController->renderPartial('_form', Array)
#11 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\yii-1.1\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#15 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(79): CController->render('create', Array)
#16 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#17 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#26 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#27 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#28 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/admin
---
2017/07/25 05:02:47 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 05:02:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 05:05:03 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 05:05:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 05:05:06 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (73)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 05:05:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: INSERT INTO `Employee` (`departmentId`, `firstName`, `lastName`, `email`, `ext`, `hireDate`, `leaveDate`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1083): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(49): EmployeeController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/create')
#14 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/create
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/create
---
2017/07/25 05:09:48 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: UPDATE `Employee` SET `id`=:yp0, `departmentId`=:yp1, `firstName`=:yp2, `lastName`=:yp3, `email`=:yp4, `ext`=:yp5, `hireDate`=:yp6, `leaveDate`=:yp7 WHERE `Employee`.`id`=2.
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (97)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 05:09:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: UPDATE `Employee` SET `id`=:yp0, `departmentId`=:yp1, `firstName`=:yp2, `lastName`=:yp3, `email`=:yp4, `ext`=:yp5, `hireDate`=:yp6, `leaveDate`=:yp7 WHERE `Employee`.`id`=2' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1756): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1130): CActiveRecord->updateByPk('2', Array)
#2 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->update(NULL)
#3 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(97): CActiveRecord->save()
#4 [internal function]: EmployeeController->actionUpdate('2')
#5 C:\xampp\htdocs\yii-1.1\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(EmployeeController), Array)
#6 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(EmployeeController), Object(ReflectionMethod), Array)
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('update')
#16 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/update')
#17 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/update/2
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/update/2
---
2017/07/25 05:13:20 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: UPDATE `Employee` SET `id`=:yp0, `departmentId`=:yp1, `firstName`=:yp2, `lastName`=:yp3, `email`=:yp4, `ext`=:yp5, `hireDate`=:yp6, `leaveDate`=:yp7 WHERE `Employee`.`id`=1.
in C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php (97)
in C:\xampp\htdocs\yii-1.1\testdrive\index.php (13)
2017/07/25 05:13:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'leaveDate' at row 1. The SQL statement executed was: UPDATE `Employee` SET `id`=:yp0, `departmentId`=:yp1, `firstName`=:yp2, `lastName`=:yp3, `email`=:yp4, `ext`=:yp5, `hireDate`=:yp6, `leaveDate`=:yp7 WHERE `Employee`.`id`=1' in C:\xampp\htdocs\yii-1.1\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1756): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(1130): CActiveRecord->updateByPk('1', Array)
#2 C:\xampp\htdocs\yii-1.1\framework\db\ar\CActiveRecord.php(811): CActiveRecord->update(NULL)
#3 C:\xampp\htdocs\yii-1.1\testdrive\protected\controllers\EmployeeController.php(97): CActiveRecord->save()
#4 [internal function]: EmployeeController->actionUpdate('1')
#5 C:\xampp\htdocs\yii-1.1\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(EmployeeController), Array)
#6 C:\xampp\htdocs\yii-1.1\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(EmployeeController), Object(ReflectionMethod), Array)
#7 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii-1.1\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii-1.1\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii-1.1\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(282): CController->run('update')
#16 C:\xampp\htdocs\yii-1.1\framework\web\CWebApplication.php(141): CWebApplication->runController('employee/update')
#17 C:\xampp\htdocs\yii-1.1\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\yii-1.1\testdrive\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yii-1.1/testdrive/index.php/employee/update/1
HTTP_REFERER=http://10.1.0.166:8080/yii-1.1/testdrive/index.php/employee/update/1
---
